version: '3.4'

services:
  msdocspythonflaskwebappquickstart:
    image: msdocspythonflaskwebappquickstart
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
